<a href="https://colab.research.google.com/github/Saamyd/Earthquakes/blob/main/Earthquake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records= []
start_year = datetime.now().year - 5
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
               'id' : p.get("id"),
                'time' : pd.to_datetime(p.get("time"), unit= "ms"),
                'updated' : pd.to_datetime(p.get("updated"), unit= "ms"),
                'latitude' : g[1] if g else None,
                'longitude' : g[0] if g else None,
                'depth_km' : g[2] if g else None,
                'mag' : p.get("mag"),
                'magType' : p.get("magtype"),
                'place' : p.get("place"),
                'status' : p.get("status"),
                'tsunami' : p.get("tsunami"),
                'alert' : p.get("alert"),
                'felt' : p.get("felt"),
                'cdi' : p.get("cdi"),
                'mmi' : p.get("mmi"),
                'sig' : p.get("sig"),
                'net' : p.get("net"),
                'code' : p.get("code"),
                'ids' : p.get("ids"),
                'sources' : p.get("sources"),
                'types' : p.get("types"),
                'nst' : p.get("nst"),
                'dmin' : p.get("dmin"),
                'rms' : p.get("rms"),
                'gap' : p.get("gap"),
                'type' : p.get("type")
            })

In [ ]:
data = pd.DataFrame(all_records)

In [ ]:
data.to_csv('global_seismic_trends_data.csv')

In [ ]:
data.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,None,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,None,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,None,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,None,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,None,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,None,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,None,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,None,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,None,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,None,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('global_seismic_trends_data.csv')

In [ ]:
data.head()

,Unnamed: 0,id,time,updated,latitude,longitude,depth_km,mag,magType,place,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,0,NaN,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,NaN,"29 km SW of Villa Basilio Nievas, Argentina",...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,1,NaN,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,NaN,Fiji region,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,2,NaN,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,NaN,"103 km SW of Basco, Philippines",...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,3,NaN,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,NaN,"114 km N of M?n?b, Iran",...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,4,NaN,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,NaN,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake

In [ ]:
data.columns

Index(['Unnamed: 0', 'id', 'time', 'updated', 'latitude', 'longitude',
       'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert',
       'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types',
       'nst', 'dmin', 'rms', 'gap', 'type'],
      dtype='object')

In [ ]:
data.shape

(121695, 27)

In [ ]:
data.to_csv('earthquake_data.csv')

In [ ]:
data.isnull().sum()

Unnamed: 0         0
id            121695
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType       121695
place              0
status             0
tsunami            0
alert         116743
felt          103235
cdi           103235
mmi           110906
sig                0
net                0
code               0
ids                0
sources            0
types              0
nst            27762
dmin            3980
rms               20
gap             3025
type               0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121695 entries, 0 to 121694
Data columns (total 27 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  121695 non-null  int64
 1   id          0 non-null       float64
 2   time        121695 non-null  object
 3   updated     121695 non-null  object
 4   latitude    121695 non-null  float64
 5   longitude   121695 non-null  float64
 6   depth_km    121695 non-null  float64
 7   mag         121695 non-null  float64
 8   magType     0 non-null       float64
 9   place       121695 non-null  object
 10  status      121695 non-null  object
 11  tsunami     121695 non-null  int64
 12  alert       4952 non-null    object
 13  felt        18460 non-null   float64
 14  cdi         18460 non-null   float64
 15  mmi         10789 non-null   float64
 16  sig         121695 non-null  int64
 17  net         121695 non-null  object
 18  code        121695 non-null  object
 19  ids         121695 non-null  object
 20  sources     121695 non-null  object
 21  types       121695 non-null  object
 22  nst         93933 non-null   float64
 23  dmin        117715 non-null  float64
 24  rms         121675 non-null  float64
 25  gap         118670 non-null  float64
 26  type        121695 non-null  object
dtypes: float64(13), int64(3), object(11)
memory usage: 25.1+ MB

In [ ]:
data['time'] = pd.to_datetime(data['time'])

In [ ]:
data['updated'] = pd.to_datetime(data['updated'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121695 entries, 0 to 121694
Data columns (total 27 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  121695 non-null  int64
 1   id          0 non-null       float64
 2   time        121695 non-null  datetime64[ns]
 3   updated     121695 non-null  datetime64[ns]
 4   latitude    121695 non-null  float64
 5   longitude   121695 non-null  float64
 6   depth_km    121695 non-null  float64
 7   mag         121695 non-null  float64
 8   magType     0 non-null       float64
 9   place       121695 non-null  object
 10  status      121695 non-null  object
 11  tsunami     121695 non-null  int64
 12  alert       4952 non-null    object
 13  felt        18460 non-null   float64
 14  cdi         18460 non-null   float64
 15  mmi         10789 non-null   float64
 16  sig         121695 non-null  int64
 17  net         121695 non-null  object
 18  code        121695 non-null  object
 19  ids         121695 non-null  object
 20  sources     121695 non-null  object
 21  types       121695 non-null  object
 22  nst         93933 non-null   float64
 23  dmin        117715 non-null  float64
 24  rms         121675 non-null  float64
 25  gap         118670 non-null  float64
 26  type        121695 non-null  object
dtypes: datetime64[ns](2), float64(13), int64(3), object(9)
memory usage: 25.1+ MB

In [ ]:
import re

In [ ]:
data['country'] = data['place'].apply(lambda x: x.split(',')[-1].strip() if pd.notnull(x) else 'Unknown')

In [ ]:
if 'alert' in data.columns:
    data['alert'] = data['alert'].str.lower()

In [ ]:
string_feilds = ['magType', 'status', 'type', 'net', 'sources', 'types']

for col in string_feilds:
    if col in data.columns:
        data[col] = data[col].astype(str).str.strip()

In [ ]:
data.isnull().sum()

Unnamed: 0         0
id            121695
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert         116743
felt          103235
cdi           103235
mmi           110906
sig                0
net                0
code               0
ids                0
sources            0
types              0
nst            27762
dmin            3980
rms               20
gap             3025
type               0
country            0
dtype: int64

In [ ]:
numeric_cols = ['mag', 'depth_km', 'nst', 'dmin', 'rms', 'gap', 'felt', 'cdi', 'mmi', 'sig' ]

for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors= 'coerce')
    data[col] = data[col].fillna(data[col].median())

In [ ]:
data.isnull().sum()

Unnamed: 0         0
id            121695
time               0
updated            0
latitude           0
longitude          0
depth_km           0
mag                0
magType            0
place              0
status             0
tsunami            0
alert         116743
felt               0
cdi                0
mmi                0
sig                0
net                0
code               0
ids                0
sources            0
types              0
nst                0
dmin               0
rms                0
gap                0
type               0
country            0
dtype: int64

In [ ]:
data.head()

,Unnamed: 0,id,time,updated,latitude,longitude,depth_km,mag,magType,place,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
0,0,NaN,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,nan,"29 km SW of Villa Basilio Nievas, Argentina",...,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",32.0,0.294,0.82,42.0,earthquake,Argentina
1,1,NaN,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,nan,Fiji region,...,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",32.0,1.471,0.29,64.0,earthquake,Fiji region
2,2,NaN,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,nan,"103 km SW of Basco, Philippines",...,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",32.0,3.057,0.69,106.0,earthquake,Philippines
3,3,NaN,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,nan,"114 km N of M?n?b, Iran",...,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",32.0,3.330,0.61,71.0,earthquake,Iran
4,4,NaN,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,nan,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",...,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",32.0,6.023,0.50,65.0,earthquake,Svalbard and Jan Mayen

In [ ]:
data.columns

Index(['Unnamed: 0', 'id', 'time', 'updated', 'latitude', 'longitude',
       'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert',
       'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types',
       'nst', 'dmin', 'rms', 'gap', 'type', 'country'],
      dtype='object')

In [ ]:
data.drop(columns= ['Unnamed: 0'], inplace= True)

In [ ]:
data.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type', 'country'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121695 entries, 0 to 121694
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         0 non-null       float64
 1   time       121695 non-null  datetime64[ns]
 2   updated    121695 non-null  datetime64[ns]
 3   latitude   121695 non-null  float64
 4   longitude  121695 non-null  float64
 5   depth_km   121695 non-null  float64
 6   mag        121695 non-null  float64
 7   magType    121695 non-null  object
 8   place      121695 non-null  object
 9   status     121695 non-null  object
 10  tsunami    121695 non-null  int64
 11  alert      4952 non-null    object
 12  felt       121695 non-null  float64
 13  cdi        121695 non-null  float64
 14  mmi        121695 non-null  float64
 15  sig        121695 non-null  int64
 16  net        121695 non-null  object
 17  code       121695 non-null  object
 18  ids        121695 non-null  object
 19  sources    121695 non-null  object
 20  types      121695 non-null  object
 21  nst        121695 non-null  float64
 22  dmin       121695 non-null  float64
 23  rms        121695 non-null  float64
 24  gap        121695 non-null  float64
 25  type       121695 non-null  object
 26  country    121695 non-null  object
dtypes: datetime64[ns](2), float64(12), int64(2), object(11)
memory usage: 25.1+ MB

In [ ]:
data['alert'].value_counts()

alert
green     4750
yellow     145
orange      29
red         28
Name: count, dtype: int64

In [ ]:
data['alert'].mode()

0    green
Name: alert, dtype: object

In [ ]:
data['alert'].fillna('green', inplace= True)

C:\Users\acer\AppData\Local\Temp\ipykernel_17552\4016975054.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['alert'].fillna('green', inplace= True)

In [ ]:
data.isnull().sum()

id           121695
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
alert             0
felt              0
cdi               0
mmi               0
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst               0
dmin              0
rms               0
gap               0
type              0
country           0
dtype: int64

In [ ]:
data['id'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
data['year'] = data['time'].dt.year
data['month'] = data['time'].dt.month
data['day'] = data['time'].dt.day
data['day_of_week'] = data['time'].dt.day_name()

In [ ]:
data['depth_category'] = data['depth_km'].apply(lambda x: 'Shallow' if x < 70 else 'Deep')

In [ ]:
data['strength_category'] = data['mag'].apply(lambda x: 'Strong/Destructive' if x >= 6.0 else 'Moderate/Mild')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121695 entries, 0 to 121694
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 0 non-null       float64
 1   time               121695 non-null  datetime64[ns]
 2   updated            121695 non-null  datetime64[ns]
 3   latitude           121695 non-null  float64
 4   longitude          121695 non-null  float64
 5   depth_km           121695 non-null  float64
 6   mag                121695 non-null  float64
 7   magType            121695 non-null  object
 8   place              121695 non-null  object
 9   status             121695 non-null  object
 10  tsunami            121695 non-null  int64
 11  alert              121695 non-null  object
 12  felt               121695 non-null  float64
 13  cdi                121695 non-null  float64
 14  mmi                121695 non-null  float64
 15  sig                121695 non-null  int64
 16  net                121695 non-null  object
 17  code               121695 non-null  object
 18  ids                121695 non-null  object
 19  sources            121695 non-null  object
 20  types              121695 non-null  object
 21  nst                121695 non-null  float64
 22  dmin               121695 non-null  float64
 23  rms                121695 non-null  float64
 24  gap                121695 non-null  float64
 25  type               121695 non-null  object
 26  country            121695 non-null  object
 27  year               121695 non-null  int32
 28  month              121695 non-null  int32
 29  day                121695 non-null  int32
 30  day_of_week        121695 non-null  object
 31  depth_category     121695 non-null  object
 32  strength_category  121695 non-null  object
dtypes: datetime64[ns](2), float64(12), int32(3), int64(2), object(14)
memory usage: 29.2+ MB

In [ ]:
data.isnull().sum()

id                   121695
time                      0
updated                   0
latitude                  0
longitude                 0
depth_km                  0
mag                       0
magType                   0
place                     0
status                    0
tsunami                   0
alert                     0
felt                      0
cdi                       0
mmi                       0
sig                       0
net                       0
code                      0
ids                       0
sources                   0
types                     0
nst                       0
dmin                      0
rms                       0
gap                       0
type                      0
country                   0
year                      0
month                     0
day                       0
day_of_week               0
depth_category            0
strength_category         0
dtype: int64

In [ ]:
data.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,rms,gap,type,country,year,month,day,day_of_week,depth_category,strength_category
0,NaN,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,nan,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,0.82,42.0,earthquake,Argentina,2021,1,31,Sunday,Shallow,Moderate/Mild
1,NaN,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,nan,Fiji region,reviewed,...,0.29,64.0,earthquake,Fiji region,2021,1,31,Sunday,Deep,Moderate/Mild
2,NaN,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,nan,"103 km SW of Basco, Philippines",reviewed,...,0.69,106.0,earthquake,Philippines,2021,1,31,Sunday,Shallow,Moderate/Mild
3,NaN,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,nan,"114 km N of M?n?b, Iran",reviewed,...,0.61,71.0,earthquake,Iran,2021,1,31,Sunday,Shallow,Moderate/Mild
4,NaN,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,nan,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,0.50,65.0,earthquake,Svalbard and Jan Mayen,2021,1,31,Sunday,Shallow,Moderate/Mild

In [ ]:
#!pip install mysql-connector-python

In [ ]:
import mysql.connector as db

In [ ]:
connect = db.connect(
    host = 'localhost',
    port = 3306,
    user = 'GUVI',
    password  = 'sami8754'
)

In [ ]:
cursor = connect.cursor()

In [ ]:
cursor.execute("CREATE DATABASE IF NOT EXISTS guvi_project1;")

In [ ]:
cursor.execute("USE guvi_project1;")

In [ ]:
print("Connected and using 'guvi_project1' successfully!")

Connected and using 'guvi_project1' successfully!

In [ ]:
#!pip install pymysql

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+pymysql://GUVI:sami8754@localhost/guvi_project1")

In [ ]:
data.to_sql("earthquakes", con= engine, if_exists= 'replace', index= False)

121695

In [ ]:
data.shape

(121695, 33)